### ISSUE TITLE
Error: "Object path was not valid: '/Scripting/Script-1'"

### ISSUE THREAD

**Issue by ave-63** [jinliu/kdotool#6]
Hi, thanks for this great tool. It was working for me 30 minutes ago; then I wrote a few more kdotool commands, put them all in a script for startup, logged out and back in to test it, and suddenly I can't run kdotool at all:

    ben@tp4 kdotool $ /home/ben/nxc/scripts/kdotool/target/debug/kdotool search
    thread 'main' panicked at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
    called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
    ben@tp4 kdotool $ RUST_BACKTRACE=1 /home/ben/nxc/scripts/kdotool/target/debug/kdotool search
    thread 'main' panicked at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
    called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
    stack backtrace:
       0: rust_begin_unwind
       1: core::panicking::panic_fmt
       2: core::result::unwrap_failed
       3: core::result::Result<T,E>::unwrap
                 at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/result.rs:1073:23
       4: <dbus::strings::Path as core::convert::From<alloc::string::String>>::from
                 at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:101:67
       5: <T as core::convert::Into<U>>::into
                 at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/convert/mod.rs:757:9
       6: dbus::blocking::Connection::with_proxy
                 at /home/ben/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/blocking.rs:161:67
       7: kdotool::main
                 at ./src/main.rs:676:24
       8: core::ops::function::FnOnce::call_once
                 at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Any ideas? I'm using arch, with KDE 6, and wayland.

**Comment by ave-63** [comment]
Update: It seems the issue comes from running kdotool with --shortcut more than once. It seems like every time I do so, it creates a line in  `kglobalshortcutsrc` with the whole `kdotool` command. If I delete those lines, and log out and back in, I am able to use kdotool again and it works. But sometimes the shortcut doesn't actually function; not sure why. But whenever I try to run kdotool again after `kdotool --shortcut ...` it fails like above. I think I'll just create my own shortcut command to run `kdotool` with no shortcut.

**Comment by jinliu** [comment]
Thanks for reporting!

I can reproduce the problem with:
```
$ kdotool --shortcut meta+k search kwrite windowactivate
$ kdotool --shortcut meta+k search kwrite windowactivate
thread 'main' panicked at /home/jin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ kdotool search kwrite
thread 'main' panicked at /home/jin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I add a `--name` argument, then it won't happen:
```
$ kdotool --shortcut meta+k --name kwrite search kwrite windowactivate
$ kdotool --shortcut meta+k --name kwrite search kwrite windowactivate
thread 'main' panicked at /home/jin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ kdotool search kwrite
```

So there is some bug in error handling when registering shortcuts. I'll look into it.

**Comment by Dyredhead** [comment]
Hi, I am having the same issue but i am not using any sort of --shortcuts.
just running `kdotool getactivewindow` causes the error to occur:
```
thread 'main' panicked at /home/dyredhead/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/dbus-0.9.7/src/strings.rs:187:1:
called `Result::unwrap()` on an `Err` value: "Object path was not valid: '/Scripting/Script-1'"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I am running the command within a script so is there any way to avoid making a shortcut?

**Comment by jinliu** [comment]
> I am running the command within a script so is there any way to avoid making a shortcut?

It won't make a shortcut unless you specified `--shortcut`. Are you getting the same error when running the command manually in a graphical terminal?

**Comment by Dyredhead** [comment]
> > I am running the command within a script so is there any way to avoid making a shortcut?
> 
> It won't make a shortcut unless you specified `--shortcut`. Are you getting the same error when running the command manually in a graphical terminal?

Yes:
![image](https://github.com/user-attachments/assets/e0db25ff-faff-45a3-a20f-aa51ea7ae07c)

Although it seems that it is sometimes inconsistent and does work. I do not know what causes it to work. After a restart it usually works for a bit.

**Comment by jinliu** [comment]
When the error happens, could you take a look in the journal to see if there are any error messages from kwin, especially those begin with "js:"? Thanks.

**Comment by Dyredhead** [comment]
I thought I had fixed the erorr since it stopped happening for a while but alas it has come back. I looked into journalctl and it actually seems to work once and then just break. 
![image](https://github.com/user-attachments/assets/62a4e09a-096a-44aa-9c1f-ffc4a7fb0e5c)

I do wonder if it has to do with my script running the command quite a few times per second but it seemed to work for a couple hours that I had the script running on and off. And now even manually running kdotool in the cli with the script nor running gives me the error.

**Comment by jinliu** [comment]
OK, perhaps I understand the problem here. You get "/Scripting/Script-1" when kwin's "loadScript" returns -1, that means a script with the same name is already loaded. And I send an empty name when you don't specify "--name", so if you run two "kdotool" commands at the same time, or if some previous script failed to stop, it will fail.

Could you help verify this theory by adding a "--name `pwgen 10 1`" parameter to kdotool in your script, so every invocation has a different name? If it works, then I'll make it the default.

Also, would you mind sharing your script, so I can test it on my machine too.

**Comment by Dyredhead** [comment]
> --name `pwgen 10 1`

Sorry for the late reply, 
the problem seems to have gone away since i added some delay between each call, about 100ms, so yes it think the problem might have been what you are describing. 

I just tested it and ran two loops simulatanosuly calling `kdotool getactivewindow` and it causes the error. 
But running `kdotool --name (pwgen 10 1) getactivewindow` doesn't (i use fish shell so the syntax is a little diffrent). 

I think it would be a good idea to add `--name (pwgen 10 1)` to every command just so simultaneous calls don't cause errors. 

As for sharing my script, its a little complicated since im not running this inside a shell script. Its part of a larger program that is acatully written in rust and i just invoke kdotool as a shell command using the `std::process::Comand` library.

it essentially looks like this in pseudocode:
```
if active_window_uuid_matches(uuid) {
    do_stuff()
    sleep(100) // in milliseconds
}

function active_window_uuid_matches(uuid) {
    return run_command("kdotool getactivewindow")
}
```

**Comment by jinliu** [comment]
OK. Thanks a lot. I'll change the code to use a random name when `--name` is not specified. Also will improve the error handling when name clashes.

**Comment by Dyredhead** [comment]
Thank you so much! I will make sure to let you know if the error happens again afterwards
